spring:
  application:
    name: authen-gateway-web
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://vnedoc-auth.vnpaytest.local/realms/vnpay-contract
            authorization-uri: https://vnedoc-auth.vnpaytest.local/realms/vnpay-contract/protocol/openid-connect/auth
            token-uri: https://vnedoc-auth.vnpaytest.local/realms/vnpay-contract/protocol/openid-connect/token
            user-info-uri: https://vnedoc-auth.vnpaytest.local/realms/vnpay-contract/protocol/openid-connect/userinfo
            jwk-set-uri: https://vnedoc-auth.vnpaytest.local/realms/vnpay-contract/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: contract-management-test
            client-secret: qzhySHeMQTEcYBL13PVK8PG8rGpERoVm
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ping
      authorizationserver:
        endpoint:
          jwk-set-uri: https://vnedoc-auth.vnpaytest.local/realms/vnpay-contract/protocol/openid-connect/certs
  cloud:
    gateway:
      mvc:
        http-client:
          type: autodetect
        routes:
          - id: redirect_route
            uri: http://localhost:8082
            predicates:
              - Path=/push
            filters:
              - RewritePath=/push, /v1/test/push
          - id: redirect_route2
            uri: http://localhost:8082
            predicates:
              - Path=/ping-to-core
            filters:
              - RewritePath=/ping-to-core, /v1/test/ping
        x-forwarded-request-headers-filter:
          host-enabled: false
          for-enabled: false
          proto-enabled: false

keycloak:
  auth-server-url: https://vnedoc-auth.vnpaytest.local/
  realm: vnpay-contract
  resource: contract-management-test
  credentials:
    secret: qzhySHeMQTEcYBL13PVK8PG8rGpERoVm
  public-client: false
  ssl-required: external
  use-resource-role-mappings: true


mail:
  additionalHeaders:
    X-Mailgun-Dkim: true
    X-Mailgun-Track: false
    X-Mailgun-Track-Clicks: false
    X-Mailgun-Track-Opens: false
